[tool.black]
line-length = 88
target-version = ['py310', 'py311', 'py312']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  __pycache__
  | build
  | dist
  | \.git
  | \.mypy_cache
  | \.pytest_cache
  | \.venv
  | venv
  | ava-worktrees
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
known_first_party = ["config", "tools", "telemetry", "unity_connection"]
skip_glob = ["ava-worktrees/*"]

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]
exclude = [
    "__pycache__",
    "build",
    "dist",
    ".git",
    ".mypy_cache", 
    ".pytest_cache",
    ".venv",
    "venv",
    "ava-worktrees"
]

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
exclude = ["ava-worktrees/"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = "-v --tb=short"
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::PendingDeprecationWarning"
]